export const GET_MUSIC_RECORDS_REQUEST = "GET_MUSIC_RECORDS_REQUEST";
export const GET_MUSIC_RECORDS_SUCCESS = "GET_MUSIC_RECORDS_SUCCESS";
export const GET_MUSIC_RECORDS_ERROR = "GET_MUSIC_RECORDS_ERROR";
